server:
  port: 8083
spring:
  application:
    name: audit
  datasource:
    url: jdbc:mysql://localhost:3306/icommerce_audit?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    show-sql: true

  flyway:
    url: jdbc:mysql://localhost:3306/mysql
    schemas: icommerce_audit
    user: root
    password: root

logging:
  level:
    ROOT: INFO
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user
